name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    defaults:
      run:
        shell: bash
        working-directory: ./terraform-scripts

    steps:
      #  Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -backend-config="./config.s3.tfbackend"

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PAT }}
#          SONARCLOUD_TOKEN: ${{ secrets.SNR }}
        run: terraform apply -auto-approve -input=false

      - name: Upload terraform lock file to artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: terraform_lock
          path: /home/runner/work/devops/devops/terraform-scripts/.terraform.lock.hcl
        continue-on-error: true
